const programs={
"01":{title:"Programa Atención Social en Red",intro:"Información, respuestas y asesoramiento para personas y familias que sospechan o ya conocen su condición autista.",html:`<p>Familias/personas que sospechan de su condición Autista. En algunos casos, ya sea por sospechas de familiares, por recomendación del centro educativo o por sospechas de su propia identidad, acuden a nosotros buscando información, respuestas y asesoramiento.</p><p>Familias/personas que tienen ya un diagnóstico. Cuando ya se cuenta con un diagnóstico, las razones para acudir a nuestra RED suele ser para buscar asesoramiento y apoyo por parte de profesionales especializados/as y familias.</p><p>La persona o familias que acuden a nuestra asociación, lo hacen porque tienen necesidades no definidas y no ofrecidas por otras entidades, generándoles desorientación después de un ir y venir a diferentes profesionales.</p>`},
"02":{title:"Programa Empoderamiento en Red",intro:"Espacios de encuentro, formación, apoyo y participación para familias y personas autistas.",html:`<h2>Red de familias</h2><p>Lugar de encuentro y formación para los familiares de personas Autistas. Sirven de orientación y aprendizaje, dando a conocer el Autismo para adquirir herramientas y estrategias que apoyarán los desafíos que aparecen en el hogar, así como mejorar la calidad de vida de la propia persona y de la familia en general.</p><p>Se llevan a cabo periódicamente abordando temas diversos. Podrá ser presencial u online. Necesitan inscripción previa. Sesiones de hora u hora y media.</p><h2>Red de Apoyo</h2><p>Programa dirigido a padres, madres, tutores legales y familiares con el que se pretende crear un lugar de encuentro, desahogo y autocuidado. Se tratan de sesiones y dinámicas enfocadas a apoyar y empoderar a las familias. Se llevan a cabo según demanda. Ofrecidas por miembros de la Junta Directiva. Podrá ser presencial u online. Sesiones de hora u hora y media.</p><h2>Red Condicion Autista</h2><p>Lugar de encuentro de personas autistas, según edad. Se ofrecerán temas a tratar y será online. Lugar donde la Comunidad Autista podrá asistir a encuentros accesibles, moderado por profesionales de la Asociación. Se trabajará la comunicación emocional, la autoestima, habilidades sociocomunicativas y todos aquellos aspectos que la Comunidad quiera tratar. Sesiones de hora u hora y media.</p>`},
"03":{title:"Atención a la Condición Autista en Centros Educativos",intro:"Coordinación y apoyo para avanzar hacia una asistencia educativa realmente inclusiva.",html:`<p>Es necesario establecer conexiones con los centros educativos, tantos de nuestros socios, como de todas aquellas personas autistas que lo necesiten. Es necesario intervenir en TODOS los contextos en los que se desarrolla la persona, y más concretamente en el contexto educativo. Para ello debe existir asistencia inclusiva a través de la coordinación del centro educativo, familias, terapeutas, voluntarios o formadores mejorando su calidad de vida.</p><ul><li>Prog. Recreos en Red.</li><li>Prog. Red difusión de la Condición Autista. Para entidades públicas y AMPAS.</li><li>Prog. Enseñanza en Red.</li></ul>`},
"04":{title:"Atención a la Condición Autista en Organismos Públicos y Privados",intro:"Sensibilización, formación y respuesta a la creciente necesidad de apoyos especializados.",html:`<h2>Programa Red difusión de la Condición Autista y Programa Enseñanza en Red.</h2><p>Los servicios públicos y privados de diferentes ámbitos (educativo, sanitario, social, etc.) constatan un significativo incremento en la demanda de apoyos especializados en todas las etapas del ciclo vital y en todos los ámbitos relevantes para la vida de las personas en el espectro del autismo, que no siempre es proporcional al reforzamiento de las medidas y recursos necesarios para darles respuesta.</p><p>Buscamos crear conciencia sobre la Condición Autista en la sociedad, informar sobre sus características y necesidades, y promover la inclusión y el apoyo a las personas con autismo y sus familias. Estos programas pueden incluir campañas informativas, eventos de sensibilización.</p>`},
"05":{title:"Programa Voluntariado en Red",intro:"Una iniciativa enfocada en el desarrollo de capital humano para el sector social.",html:`<p>El programa se centra en la capacitación y formación especializada de personas voluntarias.</p><p>El objetivo principal es profesionalizar la acción voluntaria para asegurar que la ayuda brindada cumpla con estándares de excelencia.</p><h2>Pilares del programa</h2><ul><li><b>Formación Técnica:</b> Instruir a los participantes para que ofrezcan un servicio de alta calidad.</li><li><b>Cultura del Compromiso:</b> Fomentar una implicación profunda y ética con las causas que apoyan.</li><li><b>Profesionalismo:</b> Elevar la labor del voluntario, dotándola de herramientas y habilidades que los distingan por su seriedad y eficacia.</li></ul>`},
"06":{title:"Programa de Adaptación de Entornos",intro:"Adecuamos los espacios para facilitar la inclusión, el bienestar y la participación activa.",html:`<p>Nuestro Programa de Adaptación de Entornos tiene como objetivo facilitar la inclusión, el bienestar y la participación activa de las personas mediante la adecuación de los distintos espacios en los que se desenvuelven.</p><h2>Trabajamos de forma personalizada en:</h2><ul><li><b>Entorno familiar:</b> orientación y acompañamiento para adaptar dinámicas, espacios y rutinas que favorezcan la convivencia y la autonomía.</li><li><b>Entorno educativo y formativo:</b> apoyo en centros escolares, universitarios y de formación para promover la accesibilidad, la inclusión y el rendimiento académico.</li><li><b>Entorno laboral:</b> asesoramiento para la adaptación de puestos de trabajo y entornos profesionales que fomenten la integración y el desarrollo laboral.</li><li><b>Espacios públicos y privados:</b> colaboración con entidades privadas y organismos públicos para mejorar la accesibilidad y la participación en la comunidad.</li></ul><p>Este programa se basa en un enfoque integral, práctico y colaborativo, promoviendo entornos más accesibles, inclusivos y respetuosos con la diversidad.</p>`},
"07":{title:"Programa Trabajo en Red",intro:"Servicios de apoyo para la inserción y la mejora laboral.",html:`<p>Programa Trabajo en Red ofrece servicios de apoyo para la inserción y mejora laboral. Incluye preparación de entrevistas de trabajo mediante sesiones personalizadas o grupales, elaboración y mejora del currículum vitae, y orientación laboral para definir objetivos profesionales y estrategias de búsqueda de empleo.</p><p>Las actividades pueden realizarse de forma online o presencial y tienen una duración aproximada de una hora a una hora y media, adaptándose a las necesidades de cada persona.</p>`},
"08":{title:"Programa Red Legal",intro:"Apoyo especializado desde un enfoque legal, social y mediador.",html:`<p>El Programa Red Legal ofrece un conjunto de servicios especializados orientados a apoyar a personas autistas, sus familias y el entorno social y educativo, desde un enfoque legal, social y mediador.</p><ul><li><b>Mediación familiar, educativa y social:</b> Servicio destinado a facilitar la comunicación, la resolución de conflictos y la búsqueda de acuerdos en el ámbito familiar, escolar y social, promoviendo relaciones más equilibradas y entornos inclusivos.</li><li><b>Asistencia jurídica:</b> Atención y orientación legal dirigida a personas autistas, sus familias y entidades sociales, con el objetivo de informar, asesorar y acompañar en cuestiones jurídicas relacionadas con derechos, obligaciones y procedimientos legales.</li><li><b>Elaboración de informes y gestiones administrativas:</b> Apoyo en la preparación de informes, recopilación de documentación y realización de trámites vinculados a discapacidad, dependencia, becas y ayudas, facilitando el acceso a recursos y prestaciones.</li></ul>`}}
const menu=document.querySelector('.menu');
const navlinks=document.querySelector('.navlinks');
if(menu&&navlinks){
  const closeMenu=()=>{navlinks.classList.remove('open');menu.setAttribute('aria-expanded','false')};
  menu.addEventListener('click',()=>{const isOpen=navlinks.classList.toggle('open');menu.setAttribute('aria-expanded',String(isOpen))});
  navlinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
}
document.querySelectorAll('a[href^="mailto:"]').forEach(link=>link.href='mailto:info@redautismoandalucia.org');
const footerRow=document.querySelector('footer .footer-row');
if(footerRow){
  footerRow.innerHTML='<div class="legal-links"><a href="privacidad.html">Política de privacidad</a><a href="cookies.html">Política de cookies</a></div><span>ASOCIACIÓN RED ANDALUZA CONDICION AUTISTA. CIF 24940736. nº REGISTRO 5320</span>';
}
if(!document.querySelector('link[href="legal.css"]')){
  const legalStyles=document.createElement('link');
  legalStyles.rel='stylesheet';
  legalStyles.href='legal.css';
  document.head.appendChild(legalStyles);
}
const detail=document.querySelector('[data-program]');if(detail){const id=detail.dataset.program,p=programs[id];if(p){document.querySelector('#program-number').textContent=id;document.querySelector('#program-title').textContent=p.title;document.querySelector('#program-intro').textContent=p.intro;document.querySelector('#program-content').innerHTML=p.html;}}
